=== viktorM-web/solvd_farm/src/main/resources/model/feed.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="user">
        <xs:sequence>
            <xs:element name="login" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
            <xs:element name="role">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="ADMIN"/>
                        <xs:enumeration value="FARMER"/>
                        <xs:enumeration value="SALESMAN"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:complexType name="farmType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="budget" type="xs:double"/>
            <xs:element name="user" type="user"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:complexType name="feedType">
        <xs:sequence>
            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="FOR_CHICKEN"/>
                        <xs:enumeration value="FOR_PIG"/>
                        <xs:enumeration value="FOR_COW"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="count" type="xs:double"/>
            <xs:element name="farm" type="farmType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:element name="feed" type="feedType"/>
</xs:schema>

=== viktorM-web/solvd_farm/src/main/resources/model/feed.xml
<feed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="feed.xsd">
    <type>FOR_CHICKEN</type>
    <count>99.99</count>
    <farm id="1">
        <name>Sanrise</name>
        <budget>2500.7</budget>
        <user id="1">
            <login>farmer1</login>
            <password>1111</password>
            <role>FARMER</role>
        </user>
    </farm>
</feed>
