=== viktorM-web/solvd_farm/src/main/resources/model/offer.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="user">
        <xs:sequence>
            <xs:element name="login" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
            <xs:element name="role">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="ADMIN"/>
                        <xs:enumeration value="FARMER"/>
                        <xs:enumeration value="SALESMAN"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:complexType name="shopType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="user" type="user"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:complexType name="offerType">
        <xs:sequence>
            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="SELL"/>
                        <xs:enumeration value="BUY"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="shop" type="shopType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:element name="offer" type="offerType"/>
</xs:schema>

=== viktorM-web/solvd_farm/src/main/resources/model/offer.xml
<offer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="offer.xsd">

    <type>SELL</type>
    <description>ANIMAL_COW</description>
    <price>99.99</price>
    <shop id="1">
        <name>shop2</name>
        <user id="1">
            <login>Saler2</login>
            <password>2222</password>
            <role>SALESMAN</role>
        </user>
    </shop>
</offer>
